const menus=[{name:'전주비빔밥',emoji:'🥗',tag:'든든한 한 끼',desc:'여러 가지 나물과 고추장의 감칠맛. 오후 업무도 거뜬하게 시작할 수 있는 가장 든든한 선택이에요.',price:'₩ 10,000 ~ 13,000',distance:'도보 7분 이내',mood:'든든하게',match:'92%'},{name:'들깨칼국수',emoji:'🍜',tag:'속 편한 따뜻함',desc:'고소한 들깨 국물과 부드러운 면. 바쁜 날에도 마음까지 편안해지는 따뜻한 한 그릇이에요.',price:'₩ 9,000 ~ 12,000',distance:'도보 5분 이내',mood:'가볍게',match:'89%'},{name:'제철 생선구이',emoji:'🐟',tag:'오늘의 건강식',desc:'담백한 생선과 따뜻한 밥, 정갈한 반찬. 과하지 않게 오후 컨디션을 챙기는 메뉴예요.',price:'₩ 12,000 ~ 16,000',distance:'도보 8분 이내',mood:'새로운 메뉴',match:'86%'},{name:'보쌈 정식',emoji:'🥬',tag:'함께 먹기 좋은',desc:'부드러운 고기와 아삭한 곁들임. 동료와 이야기 나누며 천천히 즐기기 좋은 메뉴예요.',price:'₩ 13,000 ~ 17,000',distance:'도보 6분 이내',mood:'동료와 함께',match:'94%'}];
const browseMenus=[{name:'냉면',emoji:'🍲',type:'시원하고 깔끔하게'},{name:'돈카츠',emoji:'🍱',type:'바삭하고 든든하게'},{name:'순두부찌개',emoji:'🍲',type:'칼칼한 국물 한 끼'},{name:'샐러드 보울',emoji:'🥙',type:'가볍고 산뜻하게'},{name:'김치찌개',emoji:'🍛',type:'익숙해서 더 좋은 맛'},{name:'쌀국수',emoji:'🍜',type:'부담 없이 따뜻하게'}];let current=menus[0],history=[];const $=id=>document.getElementById(id);function showToast(message){const toast=$('toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2300)}
function renderMenu(menu){current=menu;$('menuName').textContent=menu.name;$('menuDescription').textContent=menu.desc;$('matchText').textContent=menu.match;$('resultTitle').textContent=menu.mood==='든든하게'?'오늘의 추천':`${menu.mood} 추천`;document.querySelector('.tag').textContent=menu.tag;document.querySelector('.menu-meta').innerHTML=`<span>${menu.price}</span><span class="meta-sep"></span><span>${menu.distance}</span>`;document.querySelector('.food-art').textContent=menu.emoji;$('saveButton').classList.remove('saved');$('saveButton').innerHTML='♡ <span>저장하기</span>'}
function renderBrowse(filter=''){const grid=$('browseGrid');grid.innerHTML=browseMenus.filter(m=>m.name.includes(filter)).map(m=>`<button class="browse-item" data-name="${m.name}" type="button"><span class="browse-art">${m.emoji}</span><span><h4>${m.name}</h4><p>${m.type}</p></span></button>`).join('')||'<p class="empty-history">검색 결과가 없어요.</p>';grid.querySelectorAll('.browse-item').forEach(btn=>btn.addEventListener('click',()=>showToast(`${btn.dataset.name}을(를) 찾아볼게요.`)))}
function renderHistory(){const box=$('historyList');if(!history.length){box.innerHTML='<div class="empty-history">아직 결정한 메뉴가 없어요.<br /><span>오늘 첫 메뉴를 골라보세요.</span></div>';return}box.innerHTML=history.map(h=>`<div class="history-entry"><span class="mini-art">${h.emoji}</span><span><b>${h.name}</b><small>오늘 · 점심</small></span></div>`).join('')}
document.querySelectorAll('.pick-card').forEach(card=>card.addEventListener('click',()=>{document.querySelectorAll('.pick-card').forEach(c=>c.classList.remove('selected'));card.classList.add('selected');const options=menus.filter(m=>m.mood===card.dataset.mood);renderMenu(options[0]||menus[Math.floor(Math.random()*menus.length)]);showToast(`${card.dataset.mood} 메뉴로 바꿨어요.`)}));$('recommendButton').addEventListener('click',()=>{renderMenu(menus[Math.floor(Math.random()*menus.length)]);$('result').scrollIntoView({behavior:'smooth',block:'start'});showToast('오늘의 메뉴를 골라봤어요.')});$('shuffleButton').addEventListener('click',()=>{renderMenu(menus[Math.floor(Math.random()*menus.length)]);showToast('새로운 메뉴를 골라봤어요.')});$('saveButton').addEventListener('click',()=>{const button=$('saveButton');button.classList.toggle('saved');button.innerHTML=button.classList.contains('saved')?'♥ <span>저장했어요</span>':'♡ <span>저장하기</span>';showToast(button.classList.contains('saved')?'내 선택에 저장했어요.':'저장을 취소했어요.')});$('chooseButton').addEventListener('click',()=>{history=[current,...history.filter(h=>h.name!==current.name)].slice(0,3);renderHistory();showToast(`${current.name}, 오늘 점심은 이걸로 결정!`);$('history').scrollIntoView({behavior:'smooth',block:'center'})});$('searchInput').addEventListener('input',e=>renderBrowse(e.target.value.trim()));renderBrowse();renderHistory();
menus.push(
  {name:'제육볶음',emoji:'🍖',tag:'매콤한 활력',desc:'매콤달콤한 양념과 따뜻한 밥. 오후에 집중력이 필요할 때 기분까지 끌어올려주는 메뉴예요.',price:'₩ 10,000 ~ 14,000',distance:'도보 6분 이내',mood:'든든하게',match:'91%'},
  {name:'닭곰탕',emoji:'🍲',tag:'속 편한 보양식',desc:'담백한 닭고기와 맑은 국물. 전날 피곤했거나 차분하게 회복하고 싶은 날 잘 어울려요.',price:'₩ 9,000 ~ 12,000',distance:'도보 4분 이내',mood:'가볍게',match:'90%'},
  {name:'우동 정식',emoji:'🍜',tag:'따뜻한 면 한 그릇',desc:'쫄깃한 면과 따뜻한 국물, 간단한 곁들임까지. 부담 없이 든든하게 채우는 선택이에요.',price:'₩ 9,000 ~ 13,000',distance:'도보 5분 이내',mood:'가볍게',match:'88%'},
  {name:'마파두부 덮밥',emoji:'🍛',tag:'새로운 맛의 발견',desc:'부드러운 두부와 알싸한 소스가 밥과 잘 어울려요. 평소와 다른 점심을 원할 때 추천해요.',price:'₩ 10,000 ~ 14,000',distance:'도보 9분 이내',mood:'새로운 메뉴',match:'87%'},
  {name:'샤브샤브',emoji:'🥘',tag:'같이 먹는 즐거움',desc:'신선한 채소와 고기를 천천히 익혀 먹는 메뉴. 팀원들과 대화하며 즐기기 좋아요.',price:'₩ 15,000 ~ 20,000',distance:'도보 10분 이내',mood:'동료와 함께',match:'93%'},
  {name:'고등어구이 정식',emoji:'🐟',tag:'담백한 집밥',desc:'짭조름하게 구운 고등어와 정갈한 반찬. 자극적이지 않으면서도 만족감 있는 한 끼예요.',price:'₩ 11,000 ~ 15,000',distance:'도보 7분 이내',mood:'든든하게',match:'89%'},
  {name:'메밀국수',emoji:'🥢',tag:'산뜻한 한 끼',desc:'깔끔한 메밀면과 시원한 육수. 오후에 졸리지 않게 가볍게 먹고 싶은 날 좋아요.',price:'₩ 8,000 ~ 12,000',distance:'도보 8분 이내',mood:'가볍게',match:'85%'}
);
browseMenus.push(
  {name:'제육볶음',emoji:'🍖',type:'매콤하고 든든하게'},
  {name:'닭곰탕',emoji:'🍲',type:'맑고 따뜻하게'},
  {name:'우동 정식',emoji:'🍜',type:'부담 없이 따뜻하게'},
  {name:'마파두부 덮밥',emoji:'🍛',type:'색다르고 알싸하게'},
  {name:'샤브샤브',emoji:'🥘',type:'동료와 천천히 함께'},
  {name:'고등어구이 정식',emoji:'🐟',type:'담백한 집밥처럼'},
  {name:'메밀국수',emoji:'🥢',type:'시원하고 산뜻하게'}
);
renderBrowse();
document.title='오늘은 뭐 먹지 — 오늘 점심, 고민 끝';document.querySelectorAll('.brand span:last-child').forEach(el=>el.textContent='오늘은 뭐 먹지');document.querySelectorAll('footer span:first-child').forEach(el=>el.textContent='© 2026 오늘은 뭐 먹지');
$('chooseButton').addEventListener('click',()=>{if(window.saveLunchChoice)window.saveLunchChoice(current,'recommendation')});
const favoriteStorageKey='lunch-menu-favorites';let favoriteMenus=[];try{favoriteMenus=JSON.parse(localStorage.getItem(favoriteStorageKey)||'[]')}catch(error){console.warn('브라우저 저장소를 사용할 수 없어 이번 세션에서만 찜 목록을 표시합니다.',error)}
function menuForName(name){return menus.find(menu=>menu.name===name)||browseMenus.find(menu=>menu.name===name)||{name,emoji:'🍽️'};}
function saveFavoriteState(){try{localStorage.setItem(favoriteStorageKey,JSON.stringify(favoriteMenus))}catch(error){console.warn('찜 목록을 브라우저에 저장할 수 없습니다.',error)}}
function isFavorite(name){return favoriteMenus.some(menu=>menu.name===name);}
function renderFavoritesSection(){let section=document.getElementById('favoritesSection');if(!section){section=document.createElement('section');section.id='favoritesSection';section.className='favorites-section';document.getElementById('history').before(section)}section.innerHTML='<div class="section-heading"><div><p class="overline">YOUR FAVORITES</p><h2>찜한 메뉴</h2></div><span class="heading-note">마음에 든 메뉴를 한곳에서</span></div><div class="favorites-grid"></div>';const grid=section.querySelector('.favorites-grid');if(!favoriteMenus.length){grid.innerHTML='<div class="favorites-empty">아직 찜한 메뉴가 없어요.<br />메뉴 카드의 하트 버튼을 눌러 저장해보세요.</div>';return}favoriteMenus.forEach(menu=>{const item=document.createElement('article');item.className='favorite-item';item.innerHTML=`<span class="favorite-item-art">${menu.emoji||'🍽️'}</span><span><h4></h4><p>내가 찜한 점심 메뉴</p></span><button class="favorite-remove" type="button" aria-label="찜 해제">♥</button>`;item.querySelector('h4').textContent=menu.name;item.querySelector('.favorite-remove').addEventListener('click',()=>toggleFavorite(menu));grid.appendChild(item)})}
function updateFavoriteButtons(){document.querySelectorAll('.favorite-trigger').forEach(button=>{const name=button.dataset.name;button.textContent=isFavorite(name)?'♥':'♡';button.classList.toggle('is-favorite',isFavorite(name));button.setAttribute('aria-label',isFavorite(name)?`${name} 찜 해제`:`${name} 찜하기`)});const saveButton=document.getElementById('saveButton');if(saveButton){saveButton.classList.toggle('saved',isFavorite(current.name));saveButton.innerHTML=isFavorite(current.name)?'♥ <span>찜했어요</span>':'♡ <span>찜하기</span>'}}
function toggleFavorite(menu){const exists=isFavorite(menu.name);if(exists){favoriteMenus=favoriteMenus.filter(item=>item.name!==menu.name);showToast(`${menu.name}을(를) 찜 목록에서 뺐어요.`)}else{favoriteMenus=[...favoriteMenus,menu];if(window.saveFavorite)window.saveFavorite(menu);showToast(`${menu.name}을(를) 찜했어요.`)}saveFavoriteState();renderFavoritesSection();updateFavoriteButtons()}
function decorateBrowseCards(){document.querySelectorAll('.browse-item').forEach(card=>{if(card.querySelector('.favorite-trigger'))return;const menu=menuForName(card.dataset.name);const trigger=document.createElement('span');trigger.className='favorite-trigger';trigger.dataset.name=menu.name;trigger.setAttribute('role','button');trigger.setAttribute('tabindex','0');trigger.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();toggleFavorite(menu)});trigger.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();event.stopPropagation();toggleFavorite(menu)}});card.appendChild(trigger)});updateFavoriteButtons()}
const browseObserver=new MutationObserver(decorateBrowseCards);browseObserver.observe(document.getElementById('browseGrid'),{childList:true});decorateBrowseCards();document.getElementById('saveButton').addEventListener('click',()=>toggleFavorite(current));renderFavoritesSection();updateFavoriteButtons();new MutationObserver(updateFavoriteButtons).observe(document.getElementById('menuName'),{childList:true,characterData:true,subtree:true});
browseMenus.push({name:'김밥',emoji:'🍙',type:'간편하고 든든하게'},{name:'순대국',emoji:'🍲',type:'뜨끈하고 진하게'},{name:'치킨마요 덮밥',emoji:'🍗',type:'부드럽고 친숙하게'},{name:'오므라이스',emoji:'🍳',type:'부드럽고 포근하게'},{name:'비빔국수',emoji:'🥢',type:'매콤하고 산뜻하게'},{name:'육개장',emoji:'🍜',type:'얼큰하고 든든하게'},{name:'연어덮밥',emoji:'🍣',type:'담백하고 깔끔하게'});renderBrowse();decorateBrowseCards();
const selectedMenuButton=document.createElement('button');selectedMenuButton.type='button';selectedMenuButton.className='show-selected-button';selectedMenuButton.innerHTML='♥ <span>선택 메뉴</span>';selectedMenuButton.addEventListener('click',()=>{renderFavoritesSection();document.getElementById('favoritesSection').scrollIntoView({behavior:'smooth',block:'center'})});document.body.appendChild(selectedMenuButton);
