const rouletteMenus=[{name:'전주비빔밥',emoji:'🥗',copy:'나물과 고추장의 감칠맛으로 든든하게 시작해요.'},{name:'들깨칼국수',emoji:'🍜',copy:'고소하고 따뜻한 국물로 속을 편안하게 해요.'},{name:'제육볶음',emoji:'🍖',copy:'매콤달콤한 맛으로 오후의 활력을 채워요.'},{name:'닭곰탕',emoji:'🍲',copy:'담백한 국물 한 그릇으로 차분하게 회복해요.'},{name:'돈카츠',emoji:'🍱',copy:'바삭하고 확실한 만족감이 필요한 날이에요.'},{name:'마파두부 덮밥',emoji:'🍛',copy:'늘 먹던 메뉴 대신 오늘은 조금 색다르게 가요.'},{name:'샤브샤브',emoji:'🥘',copy:'동료들과 천천히 이야기 나누며 먹기 좋아요.'},{name:'메밀국수',emoji:'🥢',copy:'오후에 부담 없이 산뜻하게 먹을 수 있어요.'}];
const wheel=document.getElementById('wheel'),labels=document.getElementById('wheelLabels'),spinButton=document.getElementById('spinButton'),resultName=document.getElementById('resultName'),resultCopy=document.getElementById('resultCopy'),resultButton=document.getElementById('backToHome'),toast=document.getElementById('toast');let rotation=0,spinning=false;
rouletteMenus.forEach((menu,index)=>{const label=document.createElement('span'),angle=index*45+22.5,rad=angle*Math.PI/180,radius=35;label.className='wheel-label';label.style.left=`${50+Math.sin(rad)*radius}%`;label.style.top=`${50-Math.cos(rad)*radius}%`;label.innerHTML=`${menu.emoji}<br>${menu.name}`;labels.appendChild(label)});
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
spinButton.addEventListener('click',()=>{if(spinning)return;spinning=true;spinButton.disabled=true;resultButton.style.display='none';resultName.textContent='룰렛이 메뉴를 고르는 중…';resultCopy.textContent='12시 포인터가 가리키는 메뉴를 확인하고 있어요.';const selectedIndex=Math.floor(Math.random()*rouletteMenus.length),selectedCenter=selectedIndex*45+22.5,currentMod=((rotation%360)+360)%360,desired=(360-selectedCenter)%360,delta=(desired-currentMod+360)%360;rotation+=5*360+delta;wheel.style.transform=`rotate(${rotation}deg)`;setTimeout(()=>{const selected=rouletteMenus[selectedIndex];resultName.textContent=`${selected.emoji} ${selected.name}`;resultCopy.textContent=selected.copy;resultButton.style.display='inline-block';spinButton.disabled=false;spinning=false;showToast(`${selected.name}, 12시 포인터가 이 메뉴를 가리켰어요!`)},4300)});
resultButton.addEventListener('click',()=>{window.location.href='index.html#result'});
document.title='랜덤 룰렛 — 오늘은 뭐 먹지';document.querySelectorAll('.brand span:last-child').forEach(el=>el.textContent='오늘은 뭐 먹지');document.querySelectorAll('footer span:first-child').forEach(el=>el.textContent='© 2026 오늘은 뭐 먹지');
const configScript=document.createElement('script');configScript.src='supabase-config.js';document.head.appendChild(configScript);configScript.onload=()=>{const clientScript=document.createElement('script');clientScript.src='supabase-client.js';document.head.appendChild(clientScript)};
const rouletteObserver=new MutationObserver(()=>{const name=resultName.textContent.replace(/^\S+\s/,'');const menu=rouletteMenus.find(item=>item.name===name);if(menu&&window.saveLunchChoice){window.saveLunchChoice(menu,'roulette');rouletteObserver.disconnect()}});rouletteObserver.observe(resultName,{childList:true,characterData:true,subtree:true});
